name: HPS Java Post Release
on:
  release:
    types: [published]

jobs:
  attach-bin-jar:
    name: Attach the HPS Java bin JAR to a published release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Print ref
        run: |
          echo Release tag: ${{github.ref_name}}

      - name: Checkout HPS Java Source Code
        uses: actions/checkout@v2
        with:
          ref: ${{github.ref_name}}

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build the HPS Java bin jar
        run: mvn clean install -DskipTests -T4 -q

      - name: Attach the bin jar to the release
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh release upload ${{github.ref_name}} ./target/${{github.ref_name}}-bin.jar
