name: HPS Java Release

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout HPS Java Source Code
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Get release version from the snapshot in the POM
        run: echo "MAVEN_RELEASE_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout | sed s/-SNAPSHOT//g)" >> $GITHUB_ENV

      - name: Print Maven release version
        run: echo $MAVEN_RELEASE_VERSION

      - uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Configure Git User
        run: |
          git config user.email "jermccormick@gmail.com"
          git config user.name "JeremyMcCormick"

      - name: Cut HPS Java Release
        run: mvn release:prepare release:perform -B -e -s .maven_settings.xml
        env:
          CI_DEPLOY_USERNAME: ${{ secrets.CI_DEPLOY_USERNAME }}
          CI_DEPLOY_PASSWORD: ${{ secrets.CI_DEPLOY_PASSWORD }}
