name: test release
on: 
  release:
    types: [published]

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:

      - name: Dump env
        run: env | sort

      - name: Print Release Information
        env:
          TAG_NAME: ${{ github.event.release.tag_name }}
        run: echo "${TAG_NAME}"

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
          architecture: x64
           
      - name: Checkout Code
        uses: actions/checkout@v2
        
      - name: Run tests
        uses: qcastel/github-actions-maven-cmd@master
        with:
          maven-args: "clean install"
#      
# release:clean release:prepare release:perform -Dresume=false -Dgoals=deploy -DskipTests 
# -Darguments="-DskipTests -Dmaven.javadoc.skip=true" -s /nfs/slac/g/lcd/mc/prj/sw/hudson/hudson-settings-lcd.xml

#        run: mvn --batch-mode --update-snapshots package


#      - name: Release
#        uses: qcastel/github-actions-maven-release@master
#        env:
#           JAVA_HOME: /usr/lib/jvm/java-11-openjdk/
#        with:
#          maven-args: "-Dmaven.javadoc.skip=true -DskipTests -DskipITs -Dmaven.deploy.skip=true"

#jobs:
#  build:
#    runs-on: ubuntu-latest

#  steps:
#    - uses: actions/checkout@v3  

#    - name: Build and Test
#      uses: qcastel/github-actions-maven-cmd@master
#      with:
#        maven-args: "clean install -DskipTests"

#    - name: Release
#      uses: qcastel/github-actions-maven-release@master
#      env:
#        JAVA_HOME: /usr/lib/jvm/java-11-openjdk/
#      with:
#        maven-args: "-Dmaven.javadoc.skip=true -DskipTests -DskipITs -Dmaven.deploy.skip=true"