name: HPS Java Release

on:
  push:
    tags:
      - "releases/**"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:

      - name: Print release tag
        env:
          REF_NAME: ${{ github.ref_name }}
        run: echo "$REF_NAME"

      - name: Checkout source code
        uses: actions/checkout@v2
        with:
          ref: master

      # We need to check that the tag and master are exactly the same, since the tag 
      # just triggers the build and is not used directly because Maven always wants to 
      # use master. This is basically a sanity check that master looks releasable.
      - name: Check release tag
        run: |
          if [ ! -z "$(git --no-pager diff ${{ github.ref_name }})" ]; then 
            echo "ERROR: master and ${{ github.ref_name }} have diverged!"; 
            git --no-pager diff ${{ github.ref_name }}
            exit 1
          fi

      - name: Set Maven release version from POM
        run: echo "MAVEN_RELEASE_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout | sed s/-SNAPSHOT//g)" >> $GITHUB_ENV

      - name: Print Maven release version
        run: echo "$MAVEN_RELEASE_VERSION"

      - uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Configure Git User
        run: |
          git config user.email "jermccormick@gmail.com"
          git config user.name "JeremyMcCormick"

      - name: Perform Maven release
        run: mvn release:prepare release:perform -B -e -s .maven_settings.xml
        env:
          CI_DEPLOY_USERNAME: ${{ secrets.CI_DEPLOY_USERNAME }}
          CI_DEPLOY_PASSWORD: ${{ secrets.CI_DEPLOY_PASSWORD }}

      - name: Make Github release
        id: github_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.repository.name }}-${{ env.MAVEN_RELEASE_VERSION }}
          name: ${{ github.event.repository.name }} ${{ env.MAVEN_RELEASE_VERSION }}
          generate_release_notes: true
          draft: false
          prerelease: false
          files: |
            ./target/${{ github.event.repository.name }}-${{ env.MAVEN_RELEASE_VERSION }}-bin.jar
