name: Release

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "The branch to checkout when cutting the release."
        required: true
        default: "master"
      release_version:
        description: "Default version to use when preparing a release."
        required: true
        default: "auto"
      development_version:
        description: "Default version to use for new local working copy."
        required: true
        default: "auto"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
        with:
          ref: ${{ inputs.branch }}

      - name: Create version file
        run: touch .maven_version

      - name: Set input release version
        if: inputs.release_version != 'auto'
        run: |
          echo -n "-DreleaseVersion=${{ inputs.release_version }}" >> .maven_version
          echo "MAVEN_RELEASE_VERSION=${{ inputs.release_version }}" >> $GITHUB_ENV

      - name: Set default input release version
        if: inputs.release_version == 'auto'
        run: echo "MAVEN_RELEASE_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout | sed s/-SNAPSHOT//g)" >> $GITHUB_ENV

      - name: Set input development version
        if: inputs.development_version != 'auto'
        run: |
          echo "-DdevelopmentVersion=${{ inputs.development_version }}" >> .maven_version

      - uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Get email
        id: get_email
        uses: evvanErb/get-github-email-by-username-action@v1.25
        with:
          github-username: ${{ github.actor }}

      - name: Configure Git user
        run: |
          git config user.email "${{ steps.get_email.outputs.email }}"
          git config user.name "${{ github.actor }}"
          echo "Username: ${{ github.actor }}"
          echo "Email: ${{ steps.get_email.outputs.email }}"

      - name: Perform Maven release
        run: mvn release:prepare release:perform -B -e -s .maven_settings.xml $(cat .maven_version)
        env:
          CI_DEPLOY_USERNAME: ${{ secrets.CI_DEPLOY_USERNAME }}
          CI_DEPLOY_PASSWORD: ${{ secrets.CI_DEPLOY_PASSWORD }}

      - name: Make Github release
        id: github_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.repository.name }}-${{ env.MAVEN_RELEASE_VERSION }}
          name: ${{ github.event.repository.name }} ${{ env.MAVEN_RELEASE_VERSION }}
          generate_release_notes: true
          draft: false
          prerelease: false
          files: |
            ./target/${{ github.event.repository.name }}-${{ env.MAVEN_RELEASE_VERSION }}-bin.jar
