name: HPS Java Release

on:
  push:
    branches:
      - master

#on:
#  release:
#    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"

    steps:
      - uses: actions/checkout@v3
        with:
          ref: master

      - name: Build and Test
        uses: qcastel/github-actions-maven-cmd@master
        with:
          maven-args: "clean install -Ddockerfile.skip -DdockerCompose.skip -Djib.skip"

      - name: Release
        uses: qcastel/github-actions-maven-release@master
        env:
          JAVA_HOME: /usr/lib/jvm/java-1.8-openjdk/
          CI_DEPLOY_PASSWORD: ${{ secrets.CI_DEPLOY_USERNAME }}
          CI_DEPLOY_USERNAME: ${{ secrets.CI_DEPLOY_PASSWORD }}
        with:
          git-release-bot-name: "JeremyMcCormick"
          git-release-bot-email: "jermccormick@gmail.com"

          #docker-registry-id: registry.hub.docker.com
          #docker-registry-username: qcastel
          #docker-registry-password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

          #-Dmaven.deploy.skip=true
          maven-args: "-Dmaven.javadoc.skip=true -DskipTests -DskipITs"
          maven-servers: '[{"id": "lcsim-repo-releases", "username": "${CI_DEPLOY_USERNAME}", "password": "${CI_DEPLOY_PASSWORD}"}]'
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

          #gpg-enabled: true
          #gpg-key-id: ${{ secrets.GPG_KEY_ID }}
          #gpg-key: ${{ secrets.GPG_KEY }}
