name: Run Maven project tests

on:
  workflow_dispatch:
    branch-name:
          required: true
          type: string
          default: master
          description: Branch name to checkout
    
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Maven Project
        uses: ./.github/actions/setup
        with:
          branch-name: ${{ inputs.branch-name }}
        
      - name: Run tests
        run: mvn install
    