name: Run Maven project tests

on:
  workflow_dispatch:
    inputs:
      java-version:
        required: false
        type: string
        default: "1.8"
        description: Java version
      nthreads:
        required: false
        type: string
        default: "4"
        description: Number of threads for Maven build
      quiet:
        required: false
        type: boolean
        default: false
        description: Quiet output - only show errors
      debug:
        required: false
        type: boolean
        default: false
        description: Produce execution debug output
      errors:
        required: false
        type: boolean
        default: true
        description: Produce execution error messages

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Check git status
        run: git status

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: ${{ inputs.java-version }}

      - name: Create .maven_args
        run: touch .maven_args

      - name: Set Maven quiet
        run: echo -n "-q" >> .maven_args
        if: inputs.quiet

      - name: Set Maven debug
        run: echo -n " -X" >> .maven_args
        if: inputs.debug

      - name: Set Maven errors
        run: echo -n " -e" >> .maven_args
        if: inputs.errors

      - name: Set MAVEN_ARGS in environment
        run: |
          echo "MAVEN_ARGS=$(cat .maven_args)" >> $GITHUB_ENV
          rm .maven_args

      - name: Print Maven args
        run: echo ${{ env.MAVEN_ARGS }}

      - name: Run tests
        run: |
          mvn -B install -T${{ inputs.nthreads }} ${{ env.MAVEN_ARGS }}
