name: Run Maven project tests

on:
  workflow_dispatch:
    inputs:
      java-version:
        required: true
        type: string
        default: "1.8"
        description: Java version
      #branch-name:
      #  required: true
      #  type: string
      #  default: master
      #  description: Branch name to checkout
      nthreads:
        required: true
        type: string
        default: "4"
        description: Number of threads for Maven build

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Check git status
        run: git status

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: ${{ inputs.java-version }}

      - name: Run tests
        run: mvn install
