name: Run Maven project tests

on:
  workflow_dispatch: {}
    
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Maven Project
        uses: ./.github/actions/setup
        secrets: inherit

      - name: Run tests
        run: mvn install
    