name: Run Maven project tests

on:
  workflow_dispatch:
    inputs:
      java-version:
        required: false
        type: string
        default: "1.8"
        description: Java version
      nthreads:
        required: false
        type: string
        default: "4"
        description: Number of threads for Maven build
      quiet:
        required: false
        type: boolean
        default: false
        description: Quiet output - only show errors
      debug:
        required: false
        type: boolean
        default: false
        description: Produce execution debug output
      errors:
        required: false
        type: boolean
        default: true
        description: Produce execution error messages
      log-file:
        required: false
        type: string
        default: ""
        description: Log file to save output

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Check git status
        run: git status

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: ${{ inputs.java-version }}

      - name: Set default Maven arguments
        run: |
          echo "MAVEN_ARGS=" >> $GITHUB_ENV

      - name: Set Maven quiet
        run: echo "MAVEN_ARGS=${{ env.MAVEN_ARGS}}\ -q" >> $GITHUB_ENV
        if: inputs.quiet

      - name: Set Maven debug
        run: echo "MAVEN_ARGS=${{ env.MAVEN_ARGS}}\ -X" >> $GITHUB_ENls bl  V
        if: inputs.debug

      - name: Set Maven errors
        run: echo "MAVEN_ARGS=${{ env.MAVEN_ARGS}}\ -e" >> $GITHUB_ENV
        if: inputs.errors

      - name: Set Maven log file
        run: |
          mkdir -p $(dirname output/logs/${{ inputs.log-file }}) 
          echo "MAVEN_ARGS=${{ env.MAVEN_ARGS}}\ -l\ ./output/logs/${{ inputs.log-file }}" >> $GITHUB_ENV
        if: inputs.log-file != ''

      - name: Run tests
        run: |
          mvn -B install -T${{ inputs.nthreads }} ${{ env.MAVEN_ARGS }}
