name: test

on:
  workflow_dispatch:
    inputs:
      java_version:
        required: false
        type: string
        default: "1.8"
        description: Java version
      nthreads:
        required: false
        type: string
        default: "4"
        description: Number of threads for Maven build
      maven_args:
        required: false
        type: string
        default: ""
        description: Extra Maven arguments (e.g. -q, -X, -e, etc.)

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: ${{ inputs.java_version }}

      - name: Build and run tests
        run: |
          mvn -B install -T${{ inputs.nthreads }} ${{ inputs.maven_args }}
